"""add cover to events

Revision ID: 8f9f4e4b882a
Revises: d7123edf9670
Create Date: 2020-02-12 20:44:18.317044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9f4e4b882a'
down_revision = 'd7123edf9670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cover', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'cover')
    # ### end Alembic commands ###
