"""active and email_confirmed_at from users

Revision ID: d7123edf9670
Revises: 2d9cf198f585
Create Date: 2020-01-13 14:53:38.449035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7123edf9670'
down_revision = '2d9cf198f585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_confirmed_at', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed_at')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
